on:
  push:
     branches:
       - main

name: push book

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Checkout cbeauhilton copy
      uses: actions/checkout@v2
      with:
        repository: cbeauhilton/spencerfamilycookbook
        path: sfcb
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Update readme
      run: |-
        timestamp=$(date -u)
        \cp -f *.* sfcb/
        \cp -f images/* sfcb/images
        cd sfcb
        ls -la
        git config --global user.name "bot"       
        git config --global user.email "actions@users.noreply.github.com"
        git add .
        git commit -m "update: ${timestamp}. "
        git push 
